--- #YAML:1.0
name:               Daemon-Generic
version:            0.81
abstract:           framework to provide start/stop/reload for a daemon
author:
    - David Muir Sharnoff <cpan@dave.sharnoff.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    AnyEvent:           0
    Eval::LineNumbers:  0
    Event:              0
    Time::HiRes:        0
requires:
    Cwd:             0
    File::Basename:  0
    File::Flock:     0
    File::Slurp:     0
    Getopt::Long:    0
    Text::Wrap:      0
resources:
    repository:  http://github.com/muir/Daemon-Generic
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
