---
abstract: 'framework to provide start/stop/reload for a daemon'
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  AnyEvent: 0
  Eval::LineNumbers: 0
  Event: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Daemon-Generic
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  File::Basename: 0
  File::Flock: 2013.06
  File::Slurp: 0
  Getopt::Long: 0
  Text::Wrap: 0
resources:
  repository: http://github.com/muir/Daemon-Generic
version: 0.83
