--- #YAML:1.0
name:               Daemon-Generic
version:            0.71
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:             0
    File::Basename:  0
    File::Flock:     0
    File::Slurp:     0
    Getopt::Long:    0
    Text::Wrap:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
